# Site settings
title: sam6.de
email: master@sam6.de
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome blog page. I use it as start point for all of my
   open source projects and as my personal news site.
   Feel free to fork my projects or send me merge requests, if you want to fix
   bugs or improve my code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.sam6.de" # the base hostname & protocol for your site
twitter_username: sam6_de
github_username:  sam6-de

# Build settings
markdown: kramdown
